title: redone
name: redone
email: il0616@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  주로 Programming 관련 정보를 올리는 블로그.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://il0616.github.io/ # the base hostname & protocol for your site, e.g. http://example.com
repository: il0616/il0616.github.io
locale: ko

# Build settings
remote_theme: mmistakes/minimal-mistakes@4.21.0
minimal_mistakes_skin: dark
plugins:
  - jekyll-feed
  - jekyll-include-cache

include:
  - _pages

author:
  name: redone
  avatar: /assets/images/penguin.svg
  bio: 뒹굴뒹굴 # Note: Markdown is allowed
  location: 대한민국
  links:
    - label: GitHub
      icon: "fab fa-fw fa-github"
      url: https://github.com/il0616

comments:
  provider: utterances
  utterances:
    theme: github-dark
    issue_term: pathname

analytics:
  provider: google
  google:
    tracking_id: G-WD365KFNJZ
    anonymize_ip: false # default

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: true
      related: true
      show_date: true
  - scope:
      path: ""
      type: category
    values:
      author_profile: true
